#!/bin/bash


script=$1
input=$2
output=$3

sudo chmod a+x $script
touch out.txt

name=`echo "$script"|cut -f2 -d'/'`

if [[ ! -f return_code_$name ]]
then
touch return_code_$name
fi
if [[ ! -f time_$name ]]
then
touch time_$name
fi
if [[ ! -f files_$name ]]
then
touch files_$name
fi
if [[ ! -f strace_$name ]]
then
touch strace_$name
fi
if [[ ! -f ltrace_$name ]]
then
touch ltrace_$name
fi
if [[ ! -f signals_$name ]]
then
touch signals_$name
fi

$script $input out.txt

return_code=$? 2>/dev/null
time_s=`stat --format="%x" $script 2>/dev/null`
files=`find . -type f -newermt "$time_s" 2>/dev/null`
strace=`strace -c $script 2>strace_$name | grep -v "fisierul dat ca parametru nu e de tip regulat file"`
ltrace=`ltrace -c $script 2>ltrace_$name`
{ time bash $script 2>&1 >/dev/null; } 2>aux.txt
time_real=$(grep -v "fisierul dat ca parametru nu e de tip regulat file" aux.txt)
signals=`strace -e trace=signal $script 2>signals_$name`
passed=`diff $output out.txt`

if [[ ! $passed ]]
then
result="PASSED"
else
result="FAILED"
fi

echo "$return_code"> return_code_$name 
echo "$files"> files_$name
echo "$strace">>strace_$name
echo "$ltrace">>ltrace_$name
echo "$time_real"|tail -n +2>time_$name
echo "$signals">>signals_$name

echo "$result return_code_$name files_$name strace_$name ltrace_$name time_$name signals_$name"
