#!/bin/bash

declare -a scripturi
declare -a failed
declare -a passed

verificare()
{
exista=0
for element in "${scripturi[@]}"
do
if [[ $element = $valoare ]]
then
exista=1
fi
done
}

afisare_statistici()
{

list=()

for index in "${!scripturi[@]}"; do
    passed_count=${passed[$index]}
    failed_count=${failed[$index]}
    total=$((passed_count + failed_count))
    procent=$(bc <<< "scale=2; $passed_count * 100 / $total")
    list+=("${scripturi[$index]}" "${passed[$index]}" "${failed[$index]}" "$procent%")
done

zenity --list --title="Rezultate" --column="Script" --column="PASSED" --column="FAILED" --column="Procent" --height=400 --width=500 "${list[@]}"

}

initializare_contor()
{
list=()
}
add_values_to_list() {

list+=("$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9")

zenity --list --title="Rezultate" --column="Script" --column="Test" --column="Cod return" --column="Fisiere create" --column="Apeluri de sistem" --column="Apeluri de biblioteca" --column="Semnale" --column="Status" --column="Timp de executie"  --height=800 --width=1160  "${list[@]}"
}

initializare()
{
executables=$(find . -type f -executable -user $USER 2>/dev/null)

if [[ -z $executables ]]; then
    zenity --info --text="Nu s-au găsit fișiere executabile deținute de utilizatorul curent. Ieșire."
    exit 0
fi

combo_values=$(echo "$executables" | tr '\n' '|')
while true 
do
selection=$(zenity --forms --title="Meniu inițial" --text="Selectează opțiunea dorită" --add-combo="Script:" --combo-values="$combo_values" --add-entry="Fișier de intrare:" --add-entry="Fișier de ieșire:")

if [[ $? -eq 1 ]]
then
afisare_statistici
fi

if [[ $? -eq 0 ]]
then
verifica
fi

done
}

verifica()
{
if [[ -z "$selection" ]]; then
  zenity --info --text="Nicio opțiune selectată. Ieșire."
  exit 0
fi

script=$(echo "$selection" | awk -F"|" '{print $1}')
input=$(echo "$selection" | awk -F"|" '{print $2}')
output=$(echo "$selection" | awk -F"|" '{print $3}')

zenity --info --text="Opțiunea selectată: $script\nFișierul de intrare: $input\nFișierul de ieșire: $output"

result=`./date $script $input $output`
value=`echo "$result"|cut -f1 -d' '`
return_code=`echo "$result"|cut -f2 -d' '`
files=`echo "$result"|cut -f3 -d' '`
strace=`echo "$result"|cut -f4 -d' '`
ltrace=`echo "$result"|cut -f5 -d' '`
time=`echo "$result"|cut -f6 -d' '`
time_value=`cat $time| egrep "real"`
time_real=`echo "$time_value"| cut -f2 -d$'\t'`
signals=`echo "$result"|cut -f7 -d' '`
add_values_to_list $script $input $return_code $files $strace $ltrace $signals $value $time_real

valoare=$script
verificare
if [[ $exista -eq 1 ]]
then 
   for index in "${!scripturi[@]}"; do
    if [[ "${scripturi[$index]}" = "$valoare" ]]
    then
        break
    fi
done
if [[ $value = "FAILED" ]]
then
    ((failed[$index]++))
else
    ((passed[$index]++))
fi
elif [[ $exista -eq 0 ]]
then
scripturi+=("$script")
if [[ $value = "FAILED" ]]
then
    failed+=("1")
else
    passed+=("1")
fi
fi
}

initializare_contor
initializare
afisare_statistici
